name: Monitor Switch 2 Zelda

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: TESTE GIGANTE
        run: |
          echo "================================"
          echo "WORKFLOW NOVO FUNCIONANDO"
          echo "================================"
`
